### ISSUE TITLE
CommandSign not run on my 1.14 Server

### ISSUE THREAD

**Issue by cncptpr** [Nokorbis/ar-command-signs#53]
The plugin does not work on my 1.14 Server. I tried the 2.2.0 and the 2.1.2 but neither work. In the serverkonsol is a Errormessage every time I start the server and ingame, when tring any command the only answer is: "/commandsign help". Can sb help me?

**Comment by Nokorbis** [comment]
What is the error message you get in the console ?

**Comment by cncptpr** [comment]
That are the first 4 lines:

 [13:44:44] [Server thread/INFO]: [CommandSigns] Enabling CommandSigns v2.1.1
[13:44:44] [Server thread/ERROR]: Error occurred while enabling CommandSigns v2.1.1 (Is it up to date?)
java.lang.NoClassDefFoundError: be.nokorbis.spigot.commandsigns.api.menu.EditionMenu
at be.nokorbis.spigot.commandsigns.controller.NCommandSignsManager.initializeMenus(NCommandSignsManager.java:111) ~[?:?] 

The pop up when starting the server.

**Comment by Nokorbis** [comment]
That's weird, how did you get the plugin ?
Have you tried to re-download it ?

**Comment by cncptpr** [comment]
I got the plugin from the spingot side (https://www.spigotmc.org/resources/command-signs.10512/).
As mention above I tried several version all for 1.14.

**Comment by Nokorbis** [comment]
That's weird. 
Are you sure the error message is not longer ? 
Don't you have the full stack trace ? 

NoClassDefFoundError means that the .jar you downloaded isn't complete, but if that was it, nobody would be able to use it.  (And I'm pretty sure many servers use it) 
That's why I asked if you didn't get any error during the download.

I need more data from the stacktrace.

**Comment by cncptpr** [comment]
![Anmerkung 2020-05-12 154913](https://user-images.githubusercontent.com/65164803/81700081-7c3b6b80-9468-11ea-8232-4df26b162c16.png)

This is the full error message /\.
I do not think that the problem is the download, because I tried 3 different Versions and non of them worked.

**Comment by Nokorbis** [comment]
This is because you are not using spigot, you are using craftbukkit

**Comment by cncptpr** [comment]
I thought it is the same, but I will change it and try again

**Comment by cncptpr** [comment]
It is working! Thank you for helping me.
